[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
sha1 = "0.11.0-pre.3"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
